# -*- coding: utf-8 -*-
"""prophet-twii.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YAOGs12nsCTAJnNtQl_n9GaXIP75FoRA
"""

!pip install prophet==1.1
!pip install yfinance
!pip install --upgrade pandas
!pip install --upgrade pandas-datareader

import pandas as pd
from prophet import Prophet
import yfinance as yf

df = yf.download('^twii')
df = df.reset_index()
df.rename(columns = {'Date':'ds'}, inplace = True)
df.rename(columns = {'Adj Close':'y'}, inplace = True)
df

m = Prophet()
m.fit(df)

future = m.make_future_dataframe(periods=30)
future.tail(30)

forecast = m.predict(future)
forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].tail()

fig1 = m.plot(forecast)

fig2 = m.plot_components(forecast)

from prophet.plot import plot_plotly, plot_components_plotly

plot_plotly(m, forecast)

plot_components_plotly(m, forecast)